W4D5/hw/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    post 'approve', on: :member
    post 'deny', on: :member
  end
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  root to: redirect('/cats')
end

W4D5/hw/app/models/cat.rb
require 'action_view'

class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper
  # freeze ensures that constants are immutable
  CAT_COLORS = %w(black white orange brown).freeze

  # N.B. Remember, Rails 5 automatically validates the presence of
  # belongs_to associations, so we can leave the validation of owner out
  # here.
  validates :birth_date, :color, :name, :sex, :owner, presence: true
  validates :color, inclusion: CAT_COLORS, unless: -> { color.blank? }
  validates :sex, inclusion: %w(M F), if: -> { sex }
  validate :birth_date_in_the_past, if: -> { birth_date }

  has_many :rental_requests,
    class_name: :CatRentalRequest,
    dependent: :destroy

  belongs_to :owner,
    class_name: 'User',
    foreign_key: :user_id

  def age
    time_ago_in_words(birth_date)
  end

  private

  def birth_date_in_the_past
    if birth_date && birth_date > Time.now
      errors[:birth_date] << 'must be in the past'
    end
  end
end

W4D5/hw/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  # Allow unlogged in users to browse cats.
  before_action :require_user!, only: %i(new create edit update)

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = current_user.cats.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :new
    end
  end

  def edit
    @cat = current_user.cats.find(params[:id])
    render :edit
  end

  def update
    @cat = current_user.cats.find(params[:id])
    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :edit
    end
  end

  private

  def cat_params
    params.require(:cat)
      .permit(:age, :birth_date, :color, :description, :name, :sex)
  end
end

W4D5/hw/app/helpers/cats_helper.rb
module CatsHelper
end

W4D5/hw/app/views/cats/_form.html.erb
<% action = (cat.persisted? ? cat_url(cat) : cats_url) %>
<% method = (cat.persisted? ? :patch : :post) %>

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <%= auth_token %>

  <label for="cat_name">Name</label>
  <input
    type="text"
    name="cat[name]"
    id="cat_name"
    value="<%= cat.name %>">

  <br>

  <label for="cat_birth_date">Birth date</label>
  <input
    type="date"
    name="cat[birth_date]"
    id="cat_birth_date"
    value="<%= cat.birth_date %>">
  <br>

  <label for="cat_color">Color</label>
  <select name="cat[color]" id="cat_color">
    <option></option>
    <% Cat::CAT_COLORS.each do |color| %>
      <option
        <%= cat.color == color ? "selected" : "" %>
        value="<%= color %>">
        <%= color.upcase %>
      </option>
    <% end %>
  </select>
  <br>

  <input
    type="radio"
    name="cat[sex]"
    value="M"
    id="cat_sex_male"
    <%= cat.sex == "M" ? "checked" : "" %>>
  <label for="cat_sex_male">Male</label>
  <input
    type="radio"
    name="cat[sex]"
    value="F"
    id="cat_sex_female"
    <%= cat.sex == "F" ? "checked" : "" %>>
  <label for="cat_sex_female">Female</label>
  <br>
  <label>
    Description
    <textarea name="cat[description]"><%= cat.description %></textarea>
  </label>

  <br>
  <% submit_text = (cat.persisted? ? 'Update' : 'Create') + ' cat!' %>
  <input type="submit" value="<%= submit_text %>">
</form>

<%= content_for :footer do %>
<p>This is the new cats form</p>
<% end %>

W4D5/hw/app/views/cats/_req_tr.html.erb
<% is_cat_owner = current_user && current_user.owns_cat?(@cat) %>

<tr>
  <td><%= req.user.username %></td>
  <td><%= req.start_date %></td>
  <td><%= req.end_date %></td>
  <td>
    <% if req.pending? && is_cat_owner %>
        <%= button_to 'Approve', approve_cat_rental_request_url(req) %>
        <%= button_to 'Deny', deny_cat_rental_request_url(req) %>
    <% else %>
      <%= req.status %>
    <% end %>
  </td>
</tr>

W4D5/hw/app/views/cats/edit.html.erb
<section class="page"><div class="centered-box">
  <h1>Edit My Cat</h1>
  <%= render 'shared/errors' %>
  <%= render 'form', cat: @cat %>
</div></section>
<%= content_for :footer %>
<p>This is the edit page</p>
<% end %>

W4D5/hw/app/views/cats/index.html.erb
<section class="cat-index-holder">
  <nav>
    <h1>ALL OF THE CATS IN THE WORLD</h1>
    <a href="<%= new_cat_url %>">
      Add Cat
      <i class="fa fa-plus" aria-hidden="true"></i>
    </a>
  </nav>
  <section class="cat-index">
    <% @cats.each do |cat| %>
      <div class="cat-index-item">
        <div>
          <img src="http://placekitten.com/g/231/231" >
          <br /><%= link_to "Rent #{cat.name}", cat_url(cat) %>
        </div>
      </div>
    <% end %>
  </section>
</section>

<%= content_for :footer do %>
<p>This is the index page</p>
<% end %>

W4D5/hw/app/views/cats/new.html.erb
<section class="page"><div class="centered-box">
    <h1>New Cat</h1>

    <%= render 'shared/errors' %>
    <%= render 'form', cat: @cat %>
</div></section>
<%= content_for :footer do %>
<p>The new cat page</p>
<% end %>

W4D5/hw/app/views/cats/show.html.erb
<section class="page"><div class="centered-box">
  <img src="http://placekitten.com/g/300/300" >
  <h1><%= @cat.name %></h1>

  <table>
    <tr>
      <th>Attribute</th>
      <th>Value</th>
    </tr>
    <% [:age, :birth_date, :color, :sex].each do |attr_name| %>
      <tr>
        <td><%= attr_name %></td>
        <td><%= @cat.send(attr_name) %></td>
      </tr>
    <% end %>
  </table>

  <% if @cat.owner == current_user %>
    <%= link_to "Edit #{@cat.name}", edit_cat_url(@cat) %>
  <% end %>

  <br><br>
  <h1>Rental Requests</h1>
  <% if @cat.rental_requests.empty? %>
    <p><%= @cat.name %> has no rental requests.</p>
  <% else %>
    <table>
      <tr>
        <th>User</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Status</th>
      </tr>
      <% @cat.rental_requests.order('start_date').each do |req| %>
        <%= render 'req_tr', req: req %>
      <% end %>
    </table>
  <% end %>

  <% if logged_in? %>
    <%= link_to 'Make new request', new_cat_rental_request_url(cat_id: @cat.id) %>
  <% end %>
</div></section>

<%= content_for :footer do %>
<p>Showing you a cat </p>
<% end %>