W4D1/skeleton/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books, only: [:new, :create, :index, :destroy]
end

W4D1/skeleton/app/models/book.rb
class Book < ApplicationRecord
  
end

W4D1/skeleton/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    # your code here
    @books = Book.all
  end

  def new
    # your code here
  end

  def create
    # your code here
    Book.create(book_params)
    redirect_to action: 'index'
  end

  def destroy
    # your code here
    book = Book.find_by(id: params[:id])
    if book.delete
      redirect_to action: 'index'
    else
      render text: book.errors.full_messages
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :author)
  end
end

W4D1/skeleton/app/helpers/books_helper.rb
module BooksHelper
end

W4D1/skeleton/app/views/books/index.html.erb
<h1>Books</h1>

<ul>
  <% @books.each do |book| %>
    <li><%= book.title %> by <%= book.author %></li>
    <%= button_to "delete", book_url(book), method: :delete %>
    <br>
  <% end %>
</ul>

<%= link_to "Add a book", "/books/new" %>

W4D1/skeleton/app/views/books/new.html.erb
<h1>Add a Book</h1>

<% if flash.now[:errors] %>
  <ul>
    <% flash.now[:errors].each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<form action= <%= books_url %> method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label>Title
  <input type="text" name="book[title]">
  </label>
  <br>

  <label>Author
  <input type="text" name="book[author]">
  </label>
  <br>

  <input type="submit">
</form>

W4D1/skeleton/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>